diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=Ravi kumar
user.email=ravi907171@gmail.com
user.signingkey=2qwuJ4iz35UiQeMNOGOD2PSDbSq
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/ravidev9071/develop1.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
branch.master.github-pr-base-branch=ravidev9071#develop1#V2
branch.V2.github-pr-base-branch=ravidev9071#develop1#master
branch.V2.vscode-merge-base=origin/master
branch.V2.remote=origin
branch.V2.merge=refs/heads/V2
branch.V2.github-pr-owner-number=ravidev9071#develop1#3
branch.V3.github-pr-base-branch=ravidev9071#develop1#master
branch.V3.vscode-merge-base=origin/master
branch.V3.remote=origin
branch.V3.merge=refs/heads/V3
branch.V3.github-pr-owner-number=ravidev9071#develop1#4
branch.feature/V4.vscode-merge-base=origin/master
branch.feature/V4.remote=origin
branch.feature/V4.merge=refs/heads/feature/V4
branch.feature/V4.github-pr-owner-number=ravidev9071#develop1#5
branch.feature/label.vscode-merge-base=origin/master
branch.feature/label.remote=origin
branch.feature/label.merge=refs/heads/feature/label
branch.feature/label.github-pr-owner-number=ravidev9071#develop1#6
